version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    build: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node

  django_gunicorn:
    restart: always
    volumes:
      - ./django_project:/app
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - db

  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=postgres
    - POSTGRES_DB=movies
    ports:
    - 5432:5432


  nginx:
    build: ./nginx
    restart: always
    volumes:
      - .:/code
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
      - elasticsearch

volumes:
  code:
  static:
  postgres_data:

