version: '3.7'

services:

  django_gunicorn:
    restart: always
    volumes:
      - .:/code
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /usr/local/bin/gunicorn myapp.wsgi:application -w 2 -b :8000 --reload

  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=postgres
    - POSTGRES_DB=movies
    ports:
    - 5432:5432


  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  app:
  static:
  postgres_data:

