version: '3'

services:
  web:
    build: .
    network_mode: "host"
    environment:
    - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    volumes:
    - .:/app
    ports:
      - "8000:8000"
#    command:
#      "gunicorn --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application"

    depends_on:
    - db

  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=postgres
    - POSTGRES_DB=movies
    ports:
    - 5432:5432

  nginx:
    image: nginx:1.17
    container_name: ngx
    links:
      - "web"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  postgres_data: