version: '3'

services:
  web:
    build: .
    network_mode: "host"
    environment:
    - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    volumes:
    - .:/app
    depends_on:
    - db


  db:
    image: postgres
#    restart: always
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=postgres
    - POSTGRES_DB=movies
    ports:
    - 5432:5432

volumes:
  postgres_data: