version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    build: ETL1/elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node

  web_flask:
    build: Flask_app/web
    volumes:
      - ./Flask_app/web:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

  indexer_etl1:
    build: ETL1/indexer
    volumes:
      - ./ETL1/indexer:/app
    depends_on:
      - elasticsearch
    command: ["python", "ETL_mechanism.py"]