version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    build: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node

  django_gunicorn:
    restart: always
    volumes:
      - ./django_project:/app
      - static:/static
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - db
    environment:
      DEBUG: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: movies
      POSTGRES_HOST: db

  db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - .:/code
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
      - elasticsearch

  sqlite_to_pg_data_transfer:
    build: ./sqlite_to_pg_data_transfer
    volumes:
      - ./sqlite_to_pg_data_transfer:/app
    depends_on:
      - db
    command: [ "python", "transfer_data_to_pg.py" ]
    environment:
      DEBUG: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: movies
      POSTGRES_HOST: db

volumes:
  postgres_data:
  code:
  static: