version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    build: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node
    networks:
      flask_and_etl1:
        ipv4_address: 172.28.0.2

  web:
    build: web
    volumes:
      - ./web:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      flask_and_etl1:
        ipv4_address: 172.28.0.4


networks:
  flask_and_etl1:
    external: true
