version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    build: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node

  indexer:
    build: indexer
    volumes:
      - ./indexer:/app
    depends_on:
      - elasticsearch
    tty: true
