version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.0
    build: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      flask_and_etl1:
        ipv4_address: 172.28.0.2


  indexer:
    build: indexer
#    volumes:
#      - ./indexer:/app
    depends_on:
      - elasticsearch
#    command: ["python", "ETL_mechanism.py"]
#    tty: true
    networks:
      flask_and_etl1:
        ipv4_address: 172.28.0.3

networks:
  flask_and_etl1:
    external: true