# Generated by Django 3.1 on 2021-03-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210319_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(choices=[('Serial', 'Serial'), ('Film', 'Film')], verbose_name='type'),
        ),
    ]
